// Code generated by MockGen. DO NOT EDIT.
// Source: effective-architecture/steps/domain (interfaces: ILabelGenerator)
//
// Generated by this command:
//
//	mockgen -package domain -destination=label_generator_mock.go . ILabelGenerator
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockILabelGenerator is a mock of ILabelGenerator interface.
type MockILabelGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockILabelGeneratorMockRecorder
	isgomock struct{}
}

// MockILabelGeneratorMockRecorder is the mock recorder for MockILabelGenerator.
type MockILabelGeneratorMockRecorder struct {
	mock *MockILabelGenerator
}

// NewMockILabelGenerator creates a new mock instance.
func NewMockILabelGenerator(ctrl *gomock.Controller) *MockILabelGenerator {
	mock := &MockILabelGenerator{ctrl: ctrl}
	mock.recorder = &MockILabelGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILabelGenerator) EXPECT() *MockILabelGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockILabelGenerator) Generate(ctx context.Context, product Product, manufacturer Manufacturer, sku int64) (LabelFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, product, manufacturer, sku)
	ret0, _ := ret[0].(LabelFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockILabelGeneratorMockRecorder) Generate(ctx, product, manufacturer, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockILabelGenerator)(nil).Generate), ctx, product, manufacturer, sku)
}
