// Code generated by MockGen. DO NOT EDIT.
// Source: effective-architecture/steps/domain (interfaces: IServiceOzon)
//
// Generated by this command:
//
//	mockgen -package domain -destination=ozon_service_mock.go . IServiceOzon
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIServiceOzon is a mock of IServiceOzon interface.
type MockIServiceOzon struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceOzonMockRecorder
	isgomock struct{}
}

// MockIServiceOzonMockRecorder is the mock recorder for MockIServiceOzon.
type MockIServiceOzonMockRecorder struct {
	mock *MockIServiceOzon
}

// NewMockIServiceOzon creates a new mock instance.
func NewMockIServiceOzon(ctrl *gomock.Controller) *MockIServiceOzon {
	mock := &MockIServiceOzon{ctrl: ctrl}
	mock.recorder = &MockIServiceOzonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServiceOzon) EXPECT() *MockIServiceOzonMockRecorder {
	return m.recorder
}

// CategoryList mocks base method.
func (m *MockIServiceOzon) CategoryList(ctx context.Context, sku int64) ([]Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategoryList", ctx, sku)
	ret0, _ := ret[0].([]Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CategoryList indicates an expected call of CategoryList.
func (mr *MockIServiceOzonMockRecorder) CategoryList(ctx, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategoryList", reflect.TypeOf((*MockIServiceOzon)(nil).CategoryList), ctx, sku)
}
