// Code generated by MockGen. DO NOT EDIT.
// Source: effective-architecture/steps/domain (interfaces: IRepository)
//
// Generated by this command:
//
//	mockgen -package domain -destination=repository_mock.go . IRepository
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockIRepository) Cleanup(ctx context.Context, id LabelTemplateID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockIRepositoryMockRecorder) Cleanup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockIRepository)(nil).Cleanup), ctx, id)
}

// Load mocks base method.
func (m *MockIRepository) Load(ctx context.Context, aggregate *LabelTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, aggregate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockIRepositoryMockRecorder) Load(ctx, aggregate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockIRepository)(nil).Load), ctx, aggregate)
}

// LoadByCategoryList mocks base method.
func (m *MockIRepository) LoadByCategoryList(ctx context.Context, categoryList []Category) (*LabelTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByCategoryList", ctx, categoryList)
	ret0, _ := ret[0].(*LabelTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByCategoryList indicates an expected call of LoadByCategoryList.
func (mr *MockIRepositoryMockRecorder) LoadByCategoryList(ctx, categoryList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByCategoryList", reflect.TypeOf((*MockIRepository)(nil).LoadByCategoryList), ctx, categoryList)
}

// Save mocks base method.
func (m *MockIRepository) Save(ctx context.Context, aggregate *LabelTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, aggregate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIRepositoryMockRecorder) Save(ctx, aggregate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIRepository)(nil).Save), ctx, aggregate)
}
